routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Front'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('category/{slug}', 'CategoryController@showArticles')->name('front.category.articles');
    Route::get('article/{slug}', 'ArticleController@show')->name('front.article.slug');
    Route::get('articles', 'ArticleController@index')->name('front.articles');
    Route::get('/contacts', 'ContactController@index')->name('contacts');
    Route::post('/contacts', 'ContactController@sendMessage');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'AdminController@index')->name('admin.home');
    Route::resource('article', 'ArticleController');
    Route::resource('author', 'AuthorController')->except(['show', 'destroy']);
    Route::resource('category', 'CategoryController')->except(['show', 'destroy']);
    Route::resource('user', 'UserController')->only(['index', 'edit', 'update', 'destroy']);
});

app/Article.php
<?php

declare(strict_types = 1);

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;


/**
 * App\Article
 *
 * @property int $id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string $title
 * @property string $description
 * @property string $slug
 * @property int|null $author_id
 * @property-read Author|null $author
 * @property int|null $reference_article_id
 * @property-read Collection|Category[] $categories
 * @method static Builder|Article whereAuthorId($value)
 * @method static Builder|Article whereCreatedAt($value)
 * @method static Builder|Article whereDescription($value)
 * @method static Builder|Article whereId($value)
 * @method static Builder|Article whereReferenceArticleId($value)
 * @method static Builder|Article whereSlug($value)
 * @method static Builder|Article whereTitle($value)
 * @method static Builder|Article whereUpdatedAt($value)
 * @method static updateOrCreate(array $array, array $array1)
 * @mixin \Eloquent
 * @property string|null $cover
 * @method static Builder|Article whereCover($value)
 * @property string $article_type
 * @method static Builder|Article whereArticleType($value)
 */
class Article extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'title',
        'cover',
        'description',
        'slug',
        'author_id',
        'reference_article_id',
        'article_type',
    ];


    /**
     * @return BelongsTo
     */
    public function author(): BelongsTo
    {
        return $this->belongsTo(Author::class, 'author_id', 'id');
    }

    /**
     * @return BelongsToMany
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/API/ArticleController.php
<?php

declare(strict_types = 1);

namespace App\Http\Controllers\API;

use App\DTO\ArticleDTO;
use App\DTO\ArticleFullDTO;
use App\DTO\ArticlesDTO;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Throwable;
use App\Services\API\ArticleService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class ArticleController
 * @package App\Http\Controllers\API
 */
class ArticleController extends Controller
{
    /**
     * @var ArticleService
     */
    private $articleService;

    /**
     * ArticleController constructor.
     * @param ArticleService $articleService
     */
    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function getPaginate(Request $request): JsonResponse
    {
        try {
            /** @var ArticlesDTO $articles */
            $articles = $this->articleService->getPaginateData();
            return response()->json([
                'status' => true,
                'data' => collect($articles),
            ]);
        } catch (ModelNotFoundException $exception) {
            logger($exception->getMessage(), [
                    'code' => $exception->getCode(),
                    'page' => $request->page,
                    'url' => $request->fullUrl(),
                ]
            );
            return response()->json([
                'status' => false,
                'message' => $exception->getMessage(),
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        } catch (Throwable $exception) {
            return response()->json([
                'status' => false,
                'message' => $exception->getMessage(),
                'code' => JsonResponse::HTTP_INTERNAL_SERVER_ERROR,
            ], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function getFullData(Request $request): JsonResponse
    {
        try {
            $articles = $this->articleService->getFullData((int)$request->page);
            return response()->json([
                'success' => true,
                'data' => collect($articles),
            ]);
        } catch (ModelNotFoundException $exception) {
            return response()->json([
                'success' => false,
                'message' => $exception->getMessage(),
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        } catch (Throwable $exception) {
            return response()->json([
                'success' => false,
                'message' => 'Something wrong.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    /**
     * @param Request $request
     * @param int $id
     * @return ArticleFullDTO|JsonResponse
     */
    public function getFullById(Request $request, int $id)
    {
        try {
            return $this->articleService->getFullById($id);
        } catch (ModelNotFoundException $exception) {
            logger($exception->getMessage(), [
                'code' => $exception->getCode(),
                'author-id' => $id,
                'path' => $request->path(),
                'url' => $request->url(),
            ]);
            return response()->json([
                'success' => false,
                'message' => 'No data found.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        } catch (\Throwable $exception) {
            return response()->json([
                'success' => false,
                'message' => 'Something wrong.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        }
    }

    /**
     * @param Request $request
     * @param int $id
     * @return ArticleDTO|JsonResponse
     */
    public function getById(Request $request, int $id)
    {
        try {
            return $this->articleService->getById($id);
        } catch (ModelNotFoundException $exception) {
            logger($exception->getMessage(), [
                'code' => $exception->getCode(),
                'author-id' => $id,
                'path' => $request->path(),
                'url' => $request->url(),
            ]);
            return response()->json([
                'success' => false,
                'message' => 'No data found.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        } catch (\Throwable $exception) {
            return response()->json([
                'success' => false,
                'message' => 'Something wrong.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        }
    }
}

app/Http/Controllers/ArticleController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Article;
use App\Enum\ArticleTypeEnum;
use App\Http\Requests\ArticleStoreRequest;
use App\Http\Requests\ArticleUpdateRequest;
use App\Repositories\ArticleRepository;
use App\Repositories\AuthorRepository;
use App\Repositories\CategoryRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Class ArticleController
 * @package App\Http\Controllers
 */
class ArticleController extends Controller
{
    const COVER_DIRECTORY = 'articles';

    /**
     * @var AuthorRepository
     */
    private $authorRepository;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;
    /**
     * @var ArticleRepository
     */
    private $articleRepository;

    /**
     * ArticleController constructor.
     * @param AuthorRepository $authorRepository
     * @param CategoryRepository $categoryRepository
     * @param ArticleRepository $articleRepository
     */
    public function __construct(AuthorRepository $authorRepository, CategoryRepository $categoryRepository, ArticleRepository $articleRepository)
    {
        $this->middleware('auth');
        $this->authorRepository = $authorRepository;
        $this->categoryRepository = $categoryRepository;
        $this->articleRepository = $articleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {

        /** @var @var LengthAwarePaginator $articles */
        $articles = $this->articleRepository->paginate(3);

        return view('article.list', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     * @throws \Exception
     */
    public function create(): View
    {
        /** @var AuthorRepository $authors */
        $authors = $this->authorRepository->all();

        /** @var CategoryRepository $categories */
        $categories = $this->categoryRepository->all();

        $articleTypes = ArticleTypeEnum::options();

        return view('article.create', compact('authors', 'categories', 'articleTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleStoreRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(ArticleStoreRequest $request): RedirectResponse
    {
        $data = [
            'title' => $request->getTitle(),
            'cover' => $request->getCover() ? $request->getCover()->store(self::COVER_DIRECTORY) : null,
            'description' => $request->getDescription(),
            'author_id' => $request->getAuthorID(),
            'slug' => $request->getSlug(),
            'article_type' => $request->getArticleType(),
        ];

        /** @var Article $article */
        $article = $this->articleRepository->create($data);

        $article->categories()->attach($request->getCategoriesIds());

        return redirect()
            ->route('article.index')
            ->with('status', 'Article created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $articleId
     * @return View
     * @throws \Exception
     */
    public function show(int $articleId): View
    {
        $article = $this->articleRepository->find($articleId);

        return view('article.view', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $articleId
     * @return View
     * @throws \Exception
     */
    public function edit(int $articleId): View
    {
        $authors = $this->authorRepository->all();

        $categories = $this->categoryRepository->all();
        $articleTypes = ArticleTypeEnum::options();

        $article = $this->articleRepository->find($articleId);

        return view('article.edit', compact('article', 'authors', 'categories', 'articleTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticleUpdateRequest $request
     * @param int $articleId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(ArticleUpdateRequest $request, int $articleId): RedirectResponse
    {
        $data = [
            'title' => $request->getTitle(),
            'description' => $request->getDescription(),
            'author_id' => $request->getAuthorID(),
            'slug' => $request->getSlug(),
            'article_type' => $request->getArticleType(),
        ];

        if ($request->getCover()) {
            $data['cover'] = $request->getCover()->store(self::COVER_DIRECTORY);
        }

        $this->articleRepository->update($data, $articleId);

        /** @var Article $article */
        $article = $this->articleRepository->find($articleId);

        $article->categories()->sync($request->getCategoriesIds());

        return redirect()
            ->route('article.index')
            ->with('status', 'Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $articleId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy($articleId): ?RedirectResponse
    {
        try {
            $this->articleRepository->delete(['id' => $articleId]);

            return redirect()
                ->route('article.index')
                ->with('status', 'Deleted successfully!');
        } catch (\Throwable $exception) {
            return redirect()
                ->route('article.index')
                ->with('error', $exception->getMessage());
        }
    }

}

app/Http/Controllers/Front/ArticleController.php
<?php

declare (strict_types=1);

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Repositories\ArticleRepository;
use Illuminate\View\View;

class ArticleController extends Controller
{
    /** @var ArticleRepository */
    private $articleRepository;

    /**
     * ArticleController constructor.
     * @param ArticleRepository $articleRepository
     */
    public function __construct(ArticleRepository $articleRepository)
    {
        $this->articleRepository = $articleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $articles = $this->articleRepository->with(['author'])->paginate(4);

        return view('front.articles', compact('articles'));
    }

    /**
     * Display the specified resource.
     *
     * @param string $slug
     * @return View
     * @throws \Exception
     */
    public function show(string $slug): View
    {
        $article = $this->articleRepository->getBySlug($slug);

        return view('front.article', compact('article'));
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Article New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('article.store') }}" method="post" enctype="multipart/form-data">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="title">{{ __('Title') }}:</label>
                                <input id="title" class="form-control" type="text" name="title"
                                       value="{{ old('title') }}">
                                @if($errors->has('title'))
                                    <div class="alert-danger">{{ $errors->first('title') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="cover">{{ __('Cover') }}</label>
                                <input id="cover" class="form-control" type="file" name="cover" accept=".jpg, .jpeg">
                                @if($errors->has('cover'))
                                    <div class="alert-danger">{{ $errors->first('cover') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <textarea id="description" class="form-control" name="description">{{ old('description') }}</textarea>
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="article_type">{{ __('Article type') }}</label>
                                <select class="form-control" id="article_type" name="article_type">
                                    @foreach($articleTypes as $articleType)
                                        <option value="{{ $articleType['id'] }}" {{ ($articleType['id'] == old('article_type'))? 'selected' : '' }}>{{ $articleType['name'] }} | {{ $articleType['description'] }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('article_type'))
                                    <div class="alert-danger">{{ $errors->first('article_type') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="author_id">{{ __('Author') }}:</label>
                                <select class="form-control" name="author_id" id="author_id">
                                    <option value="" disabled selected> Choose author </option>
                                    @foreach($authors as $author)
                                        <option value="{{ $author->id }}" {{ ($author->id == old('author_id')? 'selected' : '') }}>{{ $author->first_name . " " . $author->last_name }}</option>
                                    @endforeach
                                </select>
                                {{--<input id="author" class="form-control" type="text" name="author" value="{{ old('author') }}">--}}
                                @if($errors->has('author_id'))
                                    <div class="alert-danger">{{ $errors->first('author_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label>{{ __('Categories') }}:</label>
                                @foreach($categories as $category)
                                    <br>
                                    <label for="category_{{ $category->id }}">
                                        <input type="checkbox" name="category[]" id="category_{{ $category->id }}"
                                               value="{{ $category->id }}"
                                                {{ (in_array($category->id, old('category', [])))? 'checked' : '' }}> {{ __($category->title) }}
                                    </label>
                                @endforeach
                                @if($errors->has('category'))
                                    <div class="alert-danger">{{ $errors->first('category') }}</div>
                                @endif
                            </div>
                            <div class="form-group">
                                <input class="btn btn-success" type="submit" value="{{ __('Save') }}">
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Article Edit
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                       <form action="{{ route('article.update', [$article->id]) }}" method="post" enctype="multipart/form-data">

                           @method('put')
                           @csrf

                           <div class="form-group">
                               <label for="title">{{ __('Title') }}:</label>
                               <input id="title" class="form-control" type="text" name="title" value="{{ old('title', $article->title) }}">
                               @if($errors->has('title'))
                                   <div class="alert-danger">{{ $errors->first('title') }}</div>
                               @endif
                           </div>

                           <div class="form-group">
                               <label for="cover">{{ __('Cover') }}</label><br>
                               @if ($article->cover)
                                   <img width="75" height="75" class="rounded-circle" src="{{ Storage::url($article->cover) }}">
                               @endif
                               <input id="cover" class="form-control" type="file" name="cover" accept=".jpg, .jpeg">
                               @if($errors->has('cover'))
                                   <div class="alert-danger">{{ $errors->first('cover') }}</div>
                               @endif
                           </div>

                           <div class="form-group">
                               <label for="description">{{ __('Description') }}:</label>
                               <textarea id="description" class="form-control" name="description">{{ old('description', $article->description) }}</textarea>
                               @if($errors->has('description'))
                                   <div class="alert-danger">{{ $errors->first('description') }}</div>
                               @endif
                           </div>

                           <div class="form-group">
                               <label for="article_type">{{ __('Article type') }}</label>
                               <select class="form-control" id="article_type" name="article_type">
                                   @foreach($articleTypes as $articleType)
                                       <option value="{{ $articleType['id'] }}" {{ ($articleType['id'] == old('article_type', $article->article_type))? 'selected' : '' }}>{{ $articleType['name'] }} | {{ $articleType['description'] }}</option>
                                   @endforeach
                               </select>
                               @if($errors->has('article_type'))
                                   <div class="alert-danger">{{ $errors->first('article_type') }}</div>
                               @endif
                           </div>

                           <div class="form-group">
                               <label for="author_id">{{ __('Author') }}:</label>
                               <select class="form-control" name="author_id" id="author_id">
                                   <option value="" disabled>{{ __('Pasirinkite autorių') }}</option>
                                   @foreach($authors as $author)
                                       <option value="{{ $author->id }}" {{ ($author->id == old('author_id', $article->author->id))? 'selected' : '' }}>{{ $author->first_name . " " . $author->last_name }}</option>
                                   @endforeach
                               </select>
                               {{--<input id="author" class="form-control" type="text" name="author" value="{{ old('author', $article->author) }}">--}}
                               @if($errors->has('author_id'))
                                   <div class="alert-danger">{{ $errors->first('author_id') }}</div>
                               @endif
                           </div>

                           <div class="form-group">
                               <label for="slug">{{ __('Slug') }}:</label>
                               <input id="slug" class="form-control" type="text" name="slug" value="{{ old('slug', $article->slug) }}">
                               @if($errors->has('slug'))
                                   <div class="alert-danger">{{ $errors->first('slug') }}</div>
                               @endif
                           </div>
                           <div class="form-group">
                               <label>{{ __('Categories') }}:</label>
                               @foreach($categories as $category)
                                   <br>
                                   <label for="category_{{ $category->id }}">
                                       <input type="checkbox" name="category[]" id="category_{{ $category->id }}"
                                              value="{{ $category->id }}"
                                       {{ in_array($category->id, old('category', $article->categories->pluck('id')->toArray()))? 'checked' : '' }}> {{ __($category->title) }}
                                   </label>
                               @endforeach
                                @if($errors->has('category'))
                                   <div class="alert-danger">{{ $errors->first('category') }}</div>
                               @endif
                           </div>
                           <div class="form-group">
                               <input class="btn btn-success" type="submit" value="{{ __('Update') }}">
                           </div>

                       </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/article/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Articles List
                        <a class="btn btn-sm btn-primary" href="{{ route('article.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>Cover</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Type</th>
                                <th>Actions</th>
                            </tr>

                            @foreach($articles as $article)
                                <tr>
                                    <td>{{ $article->id }}</td>
                                    <td>
                                        @if ($article->cover)
                                            <img src="{{ Storage::url($article->cover) }}" width="75" height="75" class="rounded-circle">
                                        @endif
                                    </td>
                                    <td>{{ $article->title }}</td>
                                    <td>{{ $article->slug }}</td>
                                    <td>{{ \App\Enum\ArticleTypeEnum::from($article->article_type)->getName() }}</td>
                                    <td>
                                        <a class='btn btn-sm btn-info' href="{{ route('article.show', [$article->id]) }}">{{ __('View') }}</a>
                                        <a class='btn btn-sm btn-success' href="{{ route('article.edit', [$article->id]) }}">{{ __('Edit') }}</a>
                                        <form action="{{ route('article.destroy', [$article->id]) }}" method="post" class="d-inline-block">
                                            @method('delete')
                                            @csrf
                                            <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                        </table>
                        <div class="row justify-content-center">{{ $articles->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection