routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Front'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('category/{slug}', 'CategoryController@showArticles')->name('front.category.articles');
    Route::get('article/{slug}', 'ArticleController@show')->name('front.article.slug');
    Route::get('articles', 'ArticleController@index')->name('front.articles');
    Route::get('/contacts', 'ContactController@index')->name('contacts');
    Route::post('/contacts', 'ContactController@sendMessage');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'AdminController@index')->name('admin.home');
    Route::resource('article', 'ArticleController');
    Route::resource('author', 'AuthorController')->except(['show', 'destroy']);
    Route::resource('category', 'CategoryController')->except(['show', 'destroy']);
    Route::resource('user', 'UserController')->only(['index', 'edit', 'update', 'destroy']);
});

app/Author.php
<?php

declare(strict_types = 1);

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Author
 *
 * @property int $id
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property string $first_name
 * @property string $last_name
 * @method static Builder|Author whereCreatedAt($value)
 * @method static Builder|Author whereFirstName($value)
 * @method static Builder|Author whereId($value)
 * @method static Builder|Author whereLastName($value)
 * @method static Builder|Author whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property int|null $reference_author_id Author id from 3rd party application
 * @method static Builder|Author whereReferenceAuthorId($value)
 * @method static updateOrCreate(array $array, array $array1)
 * @property string $location_type
 * @method static Builder|Author whereLocationType($value)
 */
class Author extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'reference_author_id',
        'location_type',
    ];
}

app/Http/Controllers/API/AuthorController.php
<?php

declare(strict_types = 1);

namespace App\Http\Controllers\API;

use App\DTO\AuthorDTO;
use App\Services\API\AuthorService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\JsonResponse;
use App\Http\Controllers\Controller;

/**
 * Class AuthorController
 * @package App\Http\Controllers\API
 */
class AuthorController extends Controller
{
    /**
     * @var AuthorService
     */
    private $authorService;

    /**
     * AuthorController constructor.
     * @param AuthorService $authorService
     */
    public function __construct(AuthorService $authorService)
    {
        $this->authorService = $authorService;
    }

    /**
     * @return AuthorDTO
     */
    public function index(): AuthorDTO
    {
        try {
            $authors = $this->authorService->getPaginateData();
            return response()->json([
                'status' => true,
                'data' => $authors->getCollection(),
                'current_page' => $authors->currentPage(),
                'total_page' => $authors->lastPage(),
            ]);
        } catch (ModelNotFoundException $exception) {
            return response()->json(
                [
                    'status' => false,
                    'message' => $exception->getMessage(),
                    'code' => $exception->getCode(),
                ],
                JsonResponse::HTTP_NOT_FOUND
            );
        } catch (\Throwable $exception) {
            return response()->json(
                [
                    'status' => false,
                    'message' => 'Something wrong',
                    'code' => JsonResponse::HTTP_INTERNAL_SERVER_ERROR,
                ],
                JsonResponse::HTTP_INTERNAL_SERVER_ERROR
            );
        }
    }

    /**
     * @param int $author
     * @return AuthorDTO
     */
    public function show(int $author): AuthorDTO
    {
        try {
            return $this->authorService->getById($author);
        } catch (ModelNotFoundException $exception) {
            return response()->json([
                'success' => false,
                'message' => 'No data found.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        } catch (\Throwable $exception) {
            return response()->json([
                'success' => false,
                'message' => 'Something wrong.',
                'code' => $exception->getCode(),
            ], JsonResponse::HTTP_NOT_FOUND);
        }
    }
}

app/Http/Controllers/AuthorController.php
<?php

declare (strict_types = 1);

namespace App\Http\Controllers;

use App\Enum\AuthorLocationTypeEnum;
use App\Http\Requests\AuthorRequest;
use App\Repositories\AuthorRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Class AuthorController
 * @package App\Http\Controllers
 */
class AuthorController extends Controller
{
    /**
     * @var AuthorRepository
     */
    private $authorRepository;

    /**
     * AuthorController constructor.
     * @param AuthorRepository $authorRepository
     */
    public function __construct(AuthorRepository $authorRepository)
    {
        $this->authorRepository = $authorRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $authors = $this->authorRepository->paginate();

        return view('author.list', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     * @throws \ReflectionException
     */
    public function create(): View
    {
        $locationTypes = AuthorLocationTypeEnum::options();

        return view('author.create', compact('locationTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AuthorRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(AuthorRequest $request): RedirectResponse
    {
        $this->authorRepository->create([
            'first_name' => $request->getFirstName(),
            'last_name' => $request->getLastName(),
            'location_type' => $request->getLocationType(),
        ]);

        return redirect()
            ->route('author.index')
            ->with('status', 'Author created successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $authorId
     * @return View
     * @throws \Exception
     */
    public function edit(int $authorId): View
    {
        $author = $this->authorRepository->find($authorId);

        $locationTypes = AuthorLocationTypeEnum::options();

        return view('author.edit', compact('author', 'locationTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AuthorRequest $request
     * @param int $authorId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(AuthorRequest $request, int $authorId): RedirectResponse
    {
        $this->authorRepository->update([
            'first_name' => $request->getFirstName(),
            'last_name' => $request->getLastName(),
            'location_type' => $request->getLocationType(),
        ], $authorId);

        return redirect()
            ->route('author.index')
            ->with('status', 'Author update successfully!');
    }
}

resources/views/author/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Author New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('author.store') }}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="first_name">{{ __('First name') }}:</label>
                                <input id="first_name" class="form-control" type="text" name="first_name"
                                       value="{{ old('first_name') }}">
                                @if($errors->has('first_name'))
                                    <div class="alert-danger">{{ $errors->first('first_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="last_name">{{ __('Last name') }}:</label>
                                <input id="last_name" class="form-control" type="text" name="last_name"
                                       value="{{ old('last_name') }}">
                                @if($errors->has('last_name'))
                                    <div class="alert-danger">{{ $errors->first('last_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="location_type">{{ __('Location type') }}:</label>
                                <select class="form-control" id="location_type" name="location_type">
                                    @foreach($locationTypes as $locationType)
                                        <option value="{{ $locationType['id'] }}" {{ ($locationType['id'] == old('location_type'))? 'selected' : '' }}>{{ $locationType['name'] }} {{ ($locationType['description'])? ' | ' . $locationType['description'] : '' }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('location_type'))
                                    <div class="alert-danger">{{ $errors->first('location_type') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success" type="submit" value="{{ __('Save') }}">
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/author/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Authror Edit
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('author.update', [$author->id]) }}" method="post">

                            {{ method_field('put') }}

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="first_name">{{ __('First name') }}:</label>
                                <input id="first_name" class="form-control" type="text" name="first_name"
                                       value="{{ old('first_name', $author->first_name) }}">
                                @if($errors->has('first_name'))
                                    <div class="alert-danger">{{ $errors->first('first_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="last_name">{{ __('Last name') }}:</label>
                                <input id="last_name" class="form-control" type="text" name="last_name"
                                       value="{{ old('last_name', $author->last_name) }}">
                                @if($errors->has('last_name'))
                                    <div class="alert-danger">{{ $errors->first('last_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="location_type">{{ __('Location type') }}:</label>
                                {{--<select class="form-control" id="location_type" name="location_type">
                                    @foreach($locationTypes as $locationType)
                                        <option value="{{ $locationType['id'] }}" {{ ($locationType['id'] == old('location_type', $author->location_type))? 'selected' : '' }}>{{ $locationType['name'] }} <em>{{ ($locationType['description'])?  ' | ' . $locationType['description'] : ''  }}</em></option>
                                    @endforeach
                                </select>--}}
                                @foreach($locationTypes as $locationType)
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="location_type" id="location_type_{{ $locationType['id'] }}" value="{{ $locationType['id'] }}" {{ ($locationType['id'] == old('location_type', $author->location_type))? 'checked' : '' }}>
                                        <label class="form-check-label" for="location_type_{{ $locationType['id'] }}">
                                            {{ $locationType['name'] }} <em>{{ ($locationType['description'])? $locationType['description'] : ''}}</em>
                                        </label>
                                    </div>
                                @endforeach
                                @if($errors->has('location_type'))
                                    <div class="alert-danger">{{ $errors->first('location_type') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success" type="submit" value="{{ __('Save') }}">
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/author/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Authors List
                        <a class="btn btn-sm btn-primary" href="{{ route('author.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>First name</th>
                                <th>Last name</th>
                                <th>Location</th>
                                <th>Actions</th>
                            </tr>

                            @foreach($authors as $author)
                                <tr>
                                    <td>{{ $author->id }}</td>
                                    <td>{{ $author->first_name }}</td>
                                    <td>{{ $author->last_name }}</td>
                                    <td>{{ \App\Enum\AuthorLocationTypeEnum::from($author->location_type)->getName() }}</td>
                                    <td>
                                        <a class='btn btn-sm btn-success' href="{{ route('author.edit', [$author->id]) }}">{{ __('Edit') }}</a>
                                    </td>
                                </tr>
                            @endforeach

                        </table>
                            <div class="row justify-content-center">{{ $authors->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection